-- ORDERS_UNIFIED Table
-- This table contains all customer orders from Excel files

CREATE TABLE [dbo].[ORDERS_UNIFIED] (
    [id] INT IDENTITY(1,1) PRIMARY KEY,
    [CUSTOMER NAME] NVARCHAR(255) NOT NULL,
    [PO NUMBER] NVARCHAR(50) NOT NULL,
    [PLANNED DELIVERY METHOD] NVARCHAR(50),
    [CUSTOMER STYLE] NVARCHAR(100),
    [CUSTOMER COLOUR DESCRIPTION] NVARCHAR(100),
    [AAG ORDER NUMBER] NVARCHAR(50),
    [ORDER TYPE] NVARCHAR(50),
    [ORDER DATE PO RECEIVED] DATE,
    [QUANTITY] INT,
    [SIZE] NVARCHAR(20),
    [created_at] DATETIME DEFAULT GETDATE(),
    [updated_at] DATETIME DEFAULT GETDATE()
);

-- Indexes for performance
CREATE INDEX [IX_ORDERS_UNIFIED_CUSTOMER_PO] ON [dbo].[ORDERS_UNIFIED] ([CUSTOMER NAME], [PO NUMBER]);
CREATE INDEX [IX_ORDERS_UNIFIED_STYLE_COLOR] ON [dbo].[ORDERS_UNIFIED] ([CUSTOMER STYLE], [CUSTOMER COLOUR DESCRIPTION]);
